#!/usr/bin/env bash
set -e

case "$1" in
    game)
        make fast
        exec ./build/webserv assets/configs/game.conf
        ;;
    siege)
        make fast
        exec ./build/webserv assets/configs/siege.conf
        ;;
    valgrind)
        make re
        exec valgrind ./build/webserv assets/configs/siege.conf
        ;;
    *)
        echo "Usage: $0 {game|siege|valgrind}" >&2
        exit 1
        ;;
esac
